[DisplayCtrl]
AEEnable=0
AWBEnable=0
ChangeGbGr=0
Gain=1.000000
AEMax=1584
AGCMode=1
AETarget=120.000000
Offset=0
CurrentTest=0
CurrentAutoSwitch=0
3DNRStrength=0.000000
Gamma=1.000000
Mode=0

RR=1.000000
RG=0.000000
RB=0.000000
GR=0.000000
GG=1.000000
GB=0.000000
BR=0.000000
BG=0.000000
BB=1.000000

Saturation=1.000000
Brightness=100.000000
Zoom=0.700000
ZoomMode=1
[Hardware]
ID=1
[Sensor]
ConfigFileName=A1+SC220AT+953+960.ini
[FPS]
Counter=30
[I2C]
IsCheck=0
IsCrcCheck=0

[Mean]

[TestInfo]
RecordFileName=D:\work\test\SmartSensDemo\x64\Debug\PrfmScn\RegComb_20191012161819.csv
RecordPath=D:\work\test\SmartSensDemo\x64\Debug\PrfmScn\
SeqNo=3

[Noise]
X0=544
Y0=382
W0=168
H0=206
X1=0
Y1=0
W1=0
H1=0
;FrameNums=10
FrameNums=2

[ISP]
DenoiseType=1
BordernType=0
FPGA_ISP=0

[System]
VM=991
Control=31
Noise=15
Config=15
Test=2047
About=255
[About]
FW1=4.501.0.6271
FW2=4.501.1.1325
SW=4.4.19.3099

[LatestFW]
FPGA=4.501.1.1317
FX3=4.501.0.2000
SW=4.4.19.3099
CheckVersion=1

[Server]
AutoCheck=0
VersionPath=\\192.168.1.10\ae\Demo\
;最后这个\必须要有
EnableServer=0
ServerIP=192.168.1.10
;内网接入Server IP地址
;ServerIP=58.246.2.226  
;外网接入Server IP地址
;Port=50555  
;//外网接入Server端口号

[FPNoffset]
;从1.7倍模拟增益到满模拟增益的测量值
Offset0=32.28
Offset1=32.22
Offset2=31.67
Offset3=30.83
Offset4=29.78
Offset5=27.48
Offset6=26.42
Offset7=25.37

[MTK_PDAF_CALIB]
FileName=[MTK]sc1300cs_pd_32x32_DLL_20210113.ini
DllVer=4

[CV_CALIBRATION]
RAW1=CV_00_Processed.raw
RAW2=CV_01_Processed.raw
RAW_OB=OB_00_Processed.raw
CV_EN=0
CV_SHOW=1


[LanguageChoose]
LangChoose=0

[SNR1]
RawFrameNum=30
MaxLux=3000
MinLux=0
StartLux=100
DelayMs=500
TxAddr=0x3315
TxValOpen=0x00
TxValClose=0x04

[SensorCtrl]
SkipPowerMessageBox=0

[EnumDevice]
DeviceName=DOTHINKEY;DEMOSENS;CZTEK;DS300/600;ROLONG;
DOTHINKEY=1
DEMOSENS=1
CZTEK=1
DS300/600=1
ROLONG=0
[Mismatch]
MaskAddr1=D:\Projects\copy\SmartSensDemo\trunk\x64\Release\mask\500acs_mask1.raw
MaskAddr2=D:\Projects\copy\SmartSensDemo\trunk\x64\Release\mask\500acs_mask2.raw

[OIS]
AUTO_OIS_ON=0
